#!/usr/local/bin/php
<!DOCTYPE html>

<html>
<h1>
League:
<style>
body{background-image:url("bg2.jpg");}

</style>


</h1>
<?php
$league="E0";

if($_POST["league"])
{
$league=$_POST["league"];
}

$connection = oci_connect($username = 'dw3',
                          $password = 'Bb1986115',
                          $connection_string = '//oracle.cise.ufl.edu/orcl');
$query = "SELECT TEAMNAME ,COUNT (*) AS NUMBERS
FROM ((SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-94' AND DAY<'1-JUL-95') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-94' AND DAY<'1-JUL-95') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-94' AND DAY<'1-JUL-95') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-94' AND DAY<'1-JUL-95') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-95' AND DAY<'1-JUL-96') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-95' AND DAY<'1-JUL-96') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-95' AND DAY<'1-JUL-96') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-95' AND DAY<'1-JUL-96') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION (SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-96' AND DAY<'1-JUL-97') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-96' AND DAY<'1-JUL-97') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-96' AND DAY<'1-JUL-97') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-96' AND DAY<'1-JUL-97') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-97' AND DAY<'1-JUL-98') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-97' AND DAY<'1-JUL-98') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-97' AND DAY<'1-JUL-98') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-97' AND DAY<'1-JUL-98') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-98' AND DAY<'1-JUL-99') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-98' AND DAY<'1-JUL-99') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-98' AND DAY<'1-JUL-99') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-98' AND DAY<'1-JUL-99') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-99' AND DAY<'1-JUL-00') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-99' AND DAY<'1-JUL-00') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-99' AND DAY<'1-JUL-00') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-99' AND DAY<'1-JUL-00') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-00' AND DAY<'1-JUL-01') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-00' AND DAY<'1-JUL-01') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-00' AND DAY<'1-JUL-01') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-00' AND DAY<'1-JUL-01') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-01' AND DAY<'1-JUL-02') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-01' AND DAY<'1-JUL-02') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-01' AND DAY<'1-JUL-02') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-01' AND DAY<'1-JUL-02') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-02' AND DAY<'1-JUL-03') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-02' AND DAY<'1-JUL-03') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-02' AND DAY<'1-JUL-03') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-02' AND DAY<'1-JUL-03') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-03' AND DAY<'1-JUL-04') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-03' AND DAY<'1-JUL-04') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-03' AND DAY<'1-JUL-04') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-03' AND DAY<'1-JUL-04') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-04' AND DAY<'1-JUL-05') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-04' AND DAY<'1-JUL-05') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-04' AND DAY<'1-JUL-05') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-04' AND DAY<'1-JUL-05') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-05' AND DAY<'1-JUL-06') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-05' AND DAY<'1-JUL-06') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-05' AND DAY<'1-JUL-06') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-05' AND DAY<'1-JUL-06') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-06' AND DAY<'1-JUL-07') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-06' AND DAY<'1-JUL-07') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-06' AND DAY<'1-JUL-07') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-06' AND DAY<'1-JUL-07') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-07' AND DAY<'1-JUL-08') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-07' AND DAY<'1-JUL-08') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-07' AND DAY<'1-JUL-08') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-07' AND DAY<'1-JUL-08') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-08' AND DAY<'1-JUL-09') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-08' AND DAY<'1-JUL-09') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-08' AND DAY<'1-JUL-09') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-08' AND DAY<'1-JUL-09') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-09' AND DAY<'1-JUL-11') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-09' AND DAY<'1-JUL-10') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-09' AND DAY<'1-JUL-10') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-09' AND DAY<'1-JUL-10') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-10' AND DAY<'1-JUL-11') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-10' AND DAY<'1-JUL-11') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-10' AND DAY<'1-JUL-11') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-10' AND DAY<'1-JUL-11') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME)UNION(SELECT TEAMNAME ,SUM(SCORE) AS SCORE
FROM (SELECT HOMETEAM AS TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-11' AND DAY<'1-JUL-12') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-11' AND DAY<'1-JUL-12') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC)
WHERE SCORE=
(SELECT MAX(SCORE)FROM (SELECT HOMETEAM AS
TEAMNAME,SUM(HT_TOTAL_SCORE) AS SCORE
FROM((SELECT HOMETEAM ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='H' AND (DAY >'01-AUG-11' AND DAY<'1-JUL-12') AND DIV='".$league."'
GROUP BY HOMETEAM)UNION
(SELECT AWAYTEAM AS TEAMNAME ,COUNT(*) *3 AS HT_TOTAL_SCORE
FROM MATCH
WHERE FTR='A' AND (DAY >'01-AUG-11' AND DAY<'1-JUL-12') AND DIV='".$league."'
GROUP BY AWAYTEAM))
GROUP BY HOMETEAM
ORDER BY SCORE DESC))
GROUP BY TEAMNAME))
GROUP BY TEAMNAME
ORDER BY NUMBERS DESC";
$statement  = oci_parse($connection, $query);
oci_execute($statement);
?>
          <table align="center" border="1px">
            <thead>
                <tr>
                    <th colspan="2">Results</th>
                </tr>  
            </thead>
            <tbody>
              <tr bgcolor="#dcdcdc"> 
                    <td align="center"><b>TEAMNAME</b></td>  
		            <td align="center"><b>NUMBERS OF CHAMPIONS</b></td> 


               </tr>
<?php
while ($row = oci_fetch_array($statement) ) {
?>              
        <tr>
	         <td><?php	echo $row['TEAMNAME'];?></td>
		     <td><?php	echo $row['NUMBERS'];?></td>


        </tr>
<?php
}
oci_free_statement($statement);
oci_close($connection);
?>
<form action="championnumber.php" method="post">
Name of league: <select name="league">
<option value="E0">Premier League</option>
<option value="E1">Championship</option>
<option value="E2">League 1</option>
<option value="E3">League 2</option>
<option value="EC">Conference</option>
<option value="D1">Bundesliga 1</option>
<option value="D2">Bundesliga 2</option>
<option value="I1">Serie A</option>
<option value="I2">Serie B</option>
<option value="SC0">Scotland Div1</option>
<option value="SC1">Scotland Div2</option>
<option value="SC2">Scotland Div3</option>
<option value="SC3">Scotland Div4</option>
<option value="SP1">La Liga Primera</option>
<option value="SP2">La Liga Segunda</option>
<option value="F1">Le Championnat</option>
<option value="F2">France Div2</option>
<option value="N1">Eredivisie</option>
<option value="B1">Jupiler League</option>
<option value="P1">Liga I</option>
<option value="T1">Futbol Ligi 1</option>
<option value="G1">Ethniki Katigoria</option>
</select>

<input type="submit" />
</form>
<br>
<a  align="center" href="index.php">Home</a><br>
<a  align="center" href="league.php">Return to League</a><br>


</html>